### ISSUE TITLE
voltronic axpert max II twin

### ISSUE THREAD

**Issue by jejeaure** [astraliens/home-assistant-inverter-xpert-king#2]
Bonjour, d'abord merci pour ton github, j'ai actuellement un onduleur ONDULEUR HYBRIDE 11KW - AXPERT MAX II 11000W TWIN - VOLTRONIC, j'ai essayé l'intégration sur home assistant et cela fonctionne, le seul souci c'est que sur mon onduleur j'ai 2 arrivées PV et du coup je n'ai qu'une seul remontée est-il possible qu'il aille cherché le deuxième PV, merci d'avance et bravo pour ton github. j'ai mis en pièce jointe le fichier protocole
[MAX Communication Protocol for HV7.2k LV5k V00 20200717.pdf](https://github.com/user-attachments/files/15739335/MAX.Communication.Protocol.for.HV7.2k.LV5k.V00.20200717.pdf)

**Comment by astraliens** [comment]
je vérifierai cela dans quelques jours, merci pour le manuel avec les détails du protocole. on dirait qu'il ne sera pas si difficile d'ajouter des informations sur PV2

**Comment by jejeaure** [comment]
Bonjour, super !!! vraiment un grand merci si tu y arrives et je ferai un
petit tuto sur https://forum.hacf.fr/ pour montrer mon montage car je
récupère les données avec un esp32 et un adaptateur ttl vers rs232 grâce à
ton intégration.
Amicalement
Jérôme

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by astraliens** [comment]
J'ai ajouté PV2 pour tester dans une branche séparée, pouvez-vous essayer de vérifier s'il fonctionne avec votre onduleur, car je n'en ai pas avec PV2

voici une nouvelle branche pour tester cette fonctionnalité https://github.com/astraliens/home-assistant-inverter-xpert-king/tree/add-pv2

**Comment by jejeaure** [comment]
Merci, je vais essayer. Question bête comment je fais pour installer cette
nouvelle branche avec HACS car il m'en propose qu'une seule version. Merci
d'avance

Le mar. 11 juin 2024 à 20:49, ASTRALiENS ***@***.***> a
écrit :

**Comment by astraliens** [comment]
Vous pouvez télécharger des fichiers à partir d'une branche distincte add-pv2 et les télécharger en utilisant ssh (sftp) vers homeassistant.
Si cela fonctionne, je fusionnerai cette branche de test avec la branche "master" et elle pourra être installée via HACS.

**Comment by jejeaure** [comment]
Bonjour, ok j’essaie demain, encore merci

Le mer. 12 juin 2024 à 18:50, ASTRALiENS ***@***.***> a
écrit :

**Comment by jejeaure** [comment]
Bonjour,
Je reviens vers vous, j'ai réussi à mettre à jour les modifs et j'ai enfin
la remonté de ma deuxième ligne de PV. Un grand grand merci pour votre
travail; du coup je vais essayer de faire un petit tuto sur le forum ha.
J'ai mis en pièce-jointe la photo de la remonté du PV2.
Jérôme

**Comment by astraliens** [comment]
merci pour vos commentaires, j'ai fusionné cette mise à jour avec la branche "master", donc maintenant cette version sera disponible pour être installée directement via HACS

**Comment by jejeaure** [comment]
Bonjour, c'est bon mise à jour faite et tout fonctionne un grand merci et
dès que j'ai le temps je fais le tuto

Le jeu. 13 juin 2024 à 18:43, ASTRALiENS ***@***.***> a
écrit :

**Comment by jejeaure** [comment]
Bonjour,
Suite à plusieurs jour d'essai j'ai remarqué que ça faisait ramer mon
raspberry 3 sous Home assistant et même planté surtout pendant les mises à
jour système, du coup je suis passé à un raspberry 4 mais idem ça pompe
énormément, je voulais juste savoir est-ce que ça viendrais du taux de
rafraîchissement des données ou alors qu'ils récupèrent trop de données.
Merci d'avance pour vos réponses
Jérôme

**Comment by astraliens** [comment]
Il n'y a pas trop de données entre l'onduleur et le HA, juste quelques courtes chaînes toutes les 5 à 10 secondes. De plus, il récupère les données de manière asynchrone, donc cela ne devrait pas affecter le thread principal.
Mais j'ai quelques blocages avec d'autres intégrations avec le même algorithme de mise à jour asynchrone des données - lorsque l'appareil distant est hors ligne et que le HA ne peut pas s'y connecter - le thread principal se bloque pendant plusieurs secondes (on dirait que c'est pour un délai de connexion dépassé), mais je ne trouve pas encore de moyen de résoudre ce problème.

**Comment by jejeaure** [comment]
Bonjour, merci pour ton retour et travail, ça vient peut-être de mon HA, à
chaque mise à jour du système je relance xpert king pour voir si c'est
mieux où pas et te tiens au courant.
Merci
Jérôme

Le jeu. 19 sept. 2024 à 06:10, ASTRALiENS ***@***.***> a
écrit :
